all: backup

backup:
	rsync -av ~/public_html/docs/net/sakai/ctools/maps/ bifrost:/admin/stats/apps/webapps/stats/maps/ctools
	rsync -av ~/public_html/docs/net/sakai/ctools bifrost:/admin/stats/apps/webapps/stats/presentations

